SHOW VARIABLES LIKE 'event_scheduler';

SET GLOBAL event_scheduler=1

-- BUAT EVENT MENGHAPUS TABEL LOG_ANGGOTA TIAP 2 JAM

CREATE OR REPLACE EVENT event_log_anggota
ON SCHEDULE EVERY 2 HOUR
DO
DELETE FROM log_anggota;


-- BUAT EVENT MENGHAPUS TABEL LOG_BUKU TIAP 2 JAM

CREATE OR REPLACE EVENT event_log_buku
ON SCHEDULE EVERY 2 HOUR
DO
DELETE FROM log_buku;